<div class="top1"></div>
<div class="container_category">

	<div class="center_allcategory">

		<div class="category_link"></div>
		<div class="category_link"></div>
		<div class="category_link"></div>
		<div class="category_link"></div>
		<div class="category_link"></div>
		<div class="category_link"></div>
		
	</div>

</div>



<h2><?php echo $this->translate('Bem vindo'); ?></h2>

<h3><?php echo $this->translate('Exemplo'); ?></h3>

<h4><?php echo $this->translate('Texto 2'); ?></h4>


<?php 
	$this->headLink()
	->prependStylesheet($this->baseUrl('/css/index.css'));
?>