<div class="top1"></div>
<div class="container_category">

	<div class="center_allcategory">

		<div class="category_link"></div>
		<div class="category_link"></div>
		<div class="category_link"></div>
		<div class="category_link"></div>
		<div class="category_link"></div>
		<div class="category_link"></div>
		
	</div>

</div>


<?php 
	$this->headLink()
	->prependStylesheet($this->baseUrl('/css/index.css'));
?>