<?php $ads = $this->paginator; ?>

<div class="container_filter">

	<div class="filter">
		
		<div class="filter_top">
			<ul>
				<li class="title_filter">FILTRO</li>
				<li class="search_filter"><input type="text" name="search_filter" /></li>
				<li class="vertical type_ads"><input type="checkbox" value="" />Empresa</li>
				<li class="vertical type_ads"><input type="checkbox" value="" />Particular</li>
			</ul>
		</div>	
		
		
		<div class="filter_center">
			<ul>
				<li class="title_filter_category">Filtrar por categorias:</li>
				<li class="filter_category"><a href="">Categoria X <span class="qtd_category">10</span></a></li>
				<li class="filter_category">Categoria X <span class="qtd_category">100</span></li>
				<li class="filter_category">Categoria X <span class="qtd_category">1000</span></li>
				<li class="filter_category">Categoria X <span class="qtd_category">10000</span></li>
			</ul>
		</div>

		<div class="filter_down">
			<ul>
				<li style="margin-bottom: 0;"><button class="filter_button">Filtrar agora</button></li>
			</ul>
		</div>
	
	</div>

</div>



<div class="ads_container" style="float: right;">
<?php echo $ads ?>

<?php foreach ($ads as $ad): ?>
	<div class="ads_title">
	
		<div class="title"><a href="<?php echo $this->url(array('controller' => 'ads', 'action' => 'show', 'id' => $ad->id), null, true); ?>"><?php echo $ad->title?></a></div>
		<div class="price">R$ <?php echo $ad->price ?></div>
		
	</div>
		<div class="ads_details">
			
			<div class="ads_mold_img">
				<div class="ads_img"><img src="/ads-image/<?php echo $ad->image ?>" /></div>
			</div>
			
			<div class="ads_desc">
				<?php echo $ad->text?>
			</div>
			
			<div class="ads_location">
				<ul>
				<li class="vertical">[ DDD 48 ]</li>
				<li class="vertical">[ Sul de Santa Catarina ]</li>
				<li class="vertical">[ Florianopolis ]</li>
				</ul>
			</div>	
			
			<div class="ads_category">
				<div class="category">Categorias: [ Casas ]</div>   
				<div class="date_public">Publicado em: 18/10/2012</div>
			</div>		
			
		</div>  
	
<?php endforeach; ?>	

<?php echo $ads ?>
</div>




<?php 
	$this->headLink()
	->prependStylesheet($this->baseUrl('/css/list_ads.css'))
	->prependStylesheet($this->baseUrl('/css/filter.css'));
?>
