<?php if (count($this->messages)) : ?>
	<ul id="messages">
	<?php foreach ($this->messages as $message) : ?>
	    <li><?php echo $this->escape($message); ?></li>
	<?php endforeach; ?>
	</ul>
<?php endif; ?>


<?php $ads = $this->paginator; ?>
<ul>
<?php foreach ($ads as $ad): ?>
	<li>
	[<a href="<?php echo $this->url(array('controller' => 'me', 'action'=> 'delete-ads', 'id' => $ad->id))?>">
	Deletar
	</a>]
	[<a href="<?php echo $this->url(array('controller' => 'me', 'action'=> 'edit-ads', 'id' => $ad->id))?>">
	Editar
	</a>]
	 <?php echo $ad->title?>  - <?php echo $ad->text?> <hr /> </li>	
<?php endforeach; ?>	
</ul>
<?php echo $ads ?>



<a href="<?php echo $this->url(array('controller' => 'me', 'action' => 'new-ads'), null, true); ?>">Criar novo anúncio</a>
