<?php if (count($this->messages)) : ?>
	<ul id="messages">
	<?php foreach ($this->messages as $message) : ?>
	    <li><?php echo $this->escape($message); ?></li>
	<?php endforeach; ?>
	</ul>
<?php endif; ?>


<form >

<div id="div-regions">
<?php
echo $this->partial('/partials/filter-region.phtml');
?>
</div>
<hr>
<div id="div-categories">
<?php
echo $this->partial('/partials/filter-category.phtml');
?>
</div>


</form>


<?php 
	$this->headScript()->setSeparator(PHP_EOL)
		->prependFile($this->baseUrl('/js/new-ads.js'));
	$this->headLink()
		->prependStylesheet($this->baseUrl('/css/new-ads.css'));		
?>
