<div id="filter-category">

	<ul rel="nivel_1">
		<?php foreach ($this->categories as $category) :?>
			<li class="li_category" rel="<?php echo $category['id'] ?>"> <?php echo $category['name'] ?></li>
		<?php endforeach; ?>
	</ul>
	
</div>

<?php 
	$this->headScript()->setSeparator(PHP_EOL)
		->prependFile($this->baseUrl('/js/partials/filter-category.js'));;

	$this->headLink()
		->prependStylesheet($this->baseUrl('/css/partials/filter-category.css'));
?>