<div id="filter-region-container">

	<div id="div-region_country" class="div-select-region select-modal" style="display: block;">
		<?php echo $this->translate('Pais')?>:
		<select name="region_country" id="region_country" class="select-onchange" >
			<option ><?php echo $this->translate('Pais')?></option>
			<option value="1" data-imagesrc="/img/flags/1.png" data-description="BR" >Brasil</option>
		</select>
	</div>

	<div id="div-region_state" class="div-select-region select-modal" >
		<?php echo $this->translate('Estado')?>:
		<select name="region_state" id="region_state" class="select-onchange" >
			<option value="0"  ><?php echo $this->translate('Estado')?>:</option>
		</select>
	</div>
	
	<div id="div-region_microregion" class="div-select-region select-modal" >
		<?php echo $this->translate('Região')?>:
		<select name="region_microregion" id="region_microregion" class="select-onchange"  >
			<option value="0"  ><?php echo $this->translate('Região')?>:</option>
		</select>
	</div>
	
	
	<div id="div-region_city" class="div-select-region select-modal" >
		<?php echo $this->translate('Cidade')?>:
		<select name="region_city" id="region_city" >
			<option value="0"  ><?php echo $this->translate('Cidade')?>:</option>
		</select>
	</div>
	
</div>


<?php 
	$this->headScript()->setSeparator(PHP_EOL)
		->prependFile($this->baseUrl('/js/partials/filter-region.js'));;

	$this->headLink()
		->prependStylesheet($this->baseUrl('/css/partials/filter-region.css'));
?>